name: CI Workflow

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3

    - name: Install Dependencies
      run: npm ci

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ hashFiles('**/package-lock.json') }}        

    - name: Compile Code
      run: npm run compile

    - name: Compile Tests
      run: npm run compile-tests

    - name: Package
      run: npm run package

    - name: Lint
      run: npm run lint
      
    - name: Run tests
      uses: GabrielBB/xvfb-action@v1.0
      with:
          run: npm test
